Finish home page
juanmanuelbyc/Capstone1 pull request #1
Opened 2022-07-27 19:51 UTC by juanmanuelbyc

Create home page and about page for capstone 1 project

2022-07-27 22:05 UTC, Ismailco requested changes
### Hi @juanmanuelbyc, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-27 22:05 UTC, Ismailco commented on README.md
> +[here!](images/screenshot.jpg)
- [ ] This link is not working kindly fix it
- [ ] Kindly include a link to a video presentation about your app, the video should have these requirements:
  - The student recorded a video presenting the features of the project.
  -  The maximum length of the video is 5 minutes.
  -  The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
  -  The video contains a demo of the project, showing the pages in different screen sizes.
  -  The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2022-07-27 22:05 UTC, Ismailco commented on README.md
> +No Online Version
- [ ] Kindly add a demo link to the online website hosted with the Github Pages, this is a requirement, and also users can see the live version of your site

2022-07-27 22:05 UTC, Ismailco commented on README.md
> +
- [ ] The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-07-27 22:05 UTC, Ismailco commented on about.html
> +            <li><a href="about.html" class="btm-header-option" aria-label="About">About</a></li>
- [ ] It should be possible to navigate between the pages, kindly add a link to the `Home` page in this `About` page so the user can navigate easily between pages, you can change the About link in the nav bar to Home
e.g `<li><a href="index.html" class="btm-header-option" aria-label="About">Home</a></li>`

2022-07-27 22:05 UTC, Ismailco commented on index.html
> +    </header>
- [ ] The pages use the exact same colors as the original design, the top bar should be darker, the color of the links in the navigation bar should be darker, and when hover should be changed to `#ec5242`

|Your design|CC design|
|-|-|
|![Screenshot_20220727_224940](https://user-images.githubusercontent.com/25227022/181379131-bef8a508-3653-48e7-afa5-911babb61be2.png)|![Screenshot_20220727_225130](https://user-images.githubusercontent.com/25227022/181379132-7118b236-adbc-48c1-b0a0-c92c6c348def.png)|

2022-07-27 22:05 UTC, Ismailco commented on index.html
> +        <div class="intro-content-container flex flex-column content-container">
- [ ] [OPTIONAL] You could use the `<article>` tag inside the section for parts that are stand-alone sections or have the same content so your code can use even more semantic HTML

2022-07-27 22:05 UTC, Ismailco commented on speakers.js
> +document.querySelector('.speakers-container').innerHTML = speakers.map((speaker) =>
- [ ] [OPTIONAL] You can add something like `window.onload = () => { Your code }` so the page populate on window load

2022-07-29 14:29 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)
Hey @juanmanuelbyc :wave:

Great work on implementing the changes requested. Your project is complete. There is nothing else to say about your project. :+1:
Go ahead and merge it. :muscle:

## Highlights :1st_place_medal:
:heavy_check_mark: Following GitFlow
:heavy_check_mark: Following Linters
:heavy_check_mark: Following the Design
:heavy_check_mark: Descriptive PR summary

### [Optional]
**[Optional]**
- [ ] Please make your PR title more descriptive such as **Final Version Capstone** :blush:
- [ ] Please make your branch name more descriptive such as **feature/capstone-project** :+1:

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 16:43 UTC, merged